audit_header: false
title: The Shawn Lepp Group
description: Shawn Lepp, a top Real Estate Agent in Durham, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Shawn Lepp
  title:
  license_number:
  about_markdown: |
    Shawn Lepp received a Bachelor of Commerce from Guelph University and has been licensed to sell real estate for over 15 years. He is married and has 2 children that he loves to spend time with.

    In his first year with Keller Williams, Shawn was ranked in the top five in Canada for sales volume and was the number one sales and listing agent at his Keller Williams Office. Based on third party analysis, Shawn as consistently been in the top 25 agents on the Toronto Real Estate Board (out of over 44,000 agents).
  market: Durham
  brand: The Shawn Lepp Group
  brokerage: Keller Williams Energy Lepp Group
  address: 111 Byron Street South<br>Whitby, Ontario L1N 4P5
  phone: 905-409-6778
  phone_type: Cell
  phone2: 905-428-8100
  phone2_type: Office
  email: shawn@shawnlepp.com
  url: http://www.shawnlepp.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheShawnLeppTeam/
  linkedin_url: https://www.linkedin.com/in/theshawnleppteam
  gplus_url: https://plus.google.com/114091879755957576821/posts
  youtube_url: https://www.youtube.com/user/shawnleppteam/videos
  twitter_url: https://twitter.com/shawnlepp
  instagram_url:
  pinterest_url: https://www.pinterest.com/slepp/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#313f7e'
  theme_color: '#130c0e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
